{{- if .Values.api.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "shepherd.fullname" . }}-api
  namespace: {{ include "shepherd.namespace" . }}
  labels:
    {{- include "shepherd.componentLabels" (dict "context" . "component" "api") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "shepherd.fullname" . }}-api
  minReplicas: {{ .Values.api.hpa.minReplicas }}
  maxReplicas: {{ .Values.api.hpa.maxReplicas }}
  metrics:
    {{- toYaml .Values.api.hpa.metrics | nindent 4 }}
{{- end }}
