apiVersion: v1
kind: Service
metadata:
  name: {{ include "shepherd.fullname" . }}-api
  namespace: {{ include "shepherd.namespace" . }}
  labels:
    {{- include "shepherd.componentLabels" (dict "context" . "component" "api") | nindent 4 }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: api
      port: {{ .Values.api.service.port }}
      targetPort: api
      protocol: TCP
    - name: internal
      port: {{ .Values.api.service.internalPort }}
      targetPort: internal
      protocol: TCP
  selector:
    {{- include "shepherd.componentSelectorLabels" (dict "context" . "component" "api") | nindent 4 }}
